# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FA3_DIMMING) += s6e3fa3-dimming.o

s6e3fa3-dimming-y := \
	s6e3fa3_dimming.o \
	s6e3fa3_tables.o \
	s6e3fa3_update.o

obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FA3_DIMMING_KUNIT_TEST) += \
	s6e3fa3-dimming-test.o

s6e3fa3-dimming-test-y := s6e3fa3_kunit.o
