/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef _DT_BINDINGS_RESET_SAMSUNG_EXYNOS7870_DISPAUD_H
#define _DT_BINDINGS_RESET_SAMSUNG_EXYNOS7870_DISPAUD_H

#define EXYNOS7870_DISPAUD_RESET_MIXER	0
#define EXYNOS7870_DISPAUD_RESET_I2S	1
#define EXYNOS7870_DISPAUD_RESET_AMP	2
#define EXYNOS7870_DISPAUD_RESET_ADMA	3

#endif
